# Generated by Django 3.2.2 on 2021-05-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeid', models.TextField(db_column='StoreID')),
                ('region', models.TextField(blank=True, db_column='Region', null=True)),
                ('store', models.CharField(blank=True, db_column='Store', max_length=20, null=True)),
                ('latitude', models.TextField(blank=True, db_column='Latitude', null=True)),
                ('longitude', models.TextField(blank=True, db_column='Longitude', null=True)),
            ],
            options={
                'db_table': 'stores',
                'managed': False,
            },
        ),
    ]
