# Generated by Django 3.2.2 on 2021-05-24 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_customers_employees_products_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customers')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.sales')),
            ],
        ),
    ]
