# Generated by Django 3.2.2 on 2021-05-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customerid', models.TextField(db_column='CustomerID', primary_key=True, serialize=False)),
                ('country', models.TextField(blank=True, db_column='Country', null=True)),
                ('customername', models.CharField(blank=True, db_column='CustomerName', max_length=30, null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=10, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=20, null=True)),
                ('postalcode', models.CharField(blank=True, db_column='PostalCode', max_length=20, null=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('salespersonid', models.TextField(db_column='SalesPersonID', primary_key=True, serialize=False)),
                ('salespersonname', models.TextField(blank=True, db_column='SalesPersonName', null=True)),
                ('title', models.CharField(blank=True, db_column='Title', max_length=30, null=True)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productid', models.TextField(db_column='ProductID', primary_key=True, serialize=False)),
                ('category', models.TextField(blank=True, db_column='Category', null=True)),
                ('product', models.CharField(blank=True, db_column='Product', max_length=20, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('salesdate', models.DateTimeField(blank=True, db_column='SalesDate', null=True)),
                ('orderid', models.SmallIntegerField(db_column='OrderID')),
                ('salespersonid', models.TextField(blank=True, db_column='SalesPersonID', null=True)),
                ('quantity', models.TextField(blank=True, db_column='Quantity', null=True)),
                ('sales', models.TextField(blank=True, db_column='Sales', null=True)),
            ],
            options={
                'db_table': 'sales',
                'managed': False,
            },
        ),
    ]
